### PR TITLE
Add graphql key to response for issue-3353

### PR DESCRIPTION
**Pull request by BlankRain**
**Proposed changes**:
Fix https://github.com/RasaHQ/rasa/issues/3353
#### how to use it? 
Sample code :

```
import requests
import json
from rasa_core_sdk import Action


class ActionDemoQuery(Action):
  def name(self):
    return "get_video"

  def run(self, dispatcher, tracker, domain):
     #you can make an api call
     # request = requests.post('http://localhost:3003/graphql',headers={'Content-Type': 'application/json'}).json()
     #  I put a mock response
     mockData={"video":"http://somehost/somevideo","playList":["movie-a","movie-b","c","d"]}
     # result = json.dumps(mockData)
     result= mockData
     dispatcher.utter_custom_json_message(result) #send the message back to the user
     return []
```
Start your action server with custom actions.

then make a request: 
```
 curl --request POST \
  --url http://localhost:5005/conversations/jack/execute \
  --header 'content-type: application/json' \
  --data '{
    "action": "get_video"
  }' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   907  100   876  100    31  15368    543 --:--:-- --:--:-- --:--:-- 15912
{
    "messages": [
        {
            "graphql": [
                {
                    "playList": [
                        "movie-a",
                        "movie-b",
                        "c",
                        "d"
                    ],
                    "video": "http://somehost/somevideo"
                }
            ],
            "recipient_id": "jack"
        }
    ],
    "tracker": {
        "active_form": {},
        "events": [
            {
                "confidence": null,
                "event": "action",
                "name": "action_listen",
                "policy": null,
                "timestamp": 1556700567.1577513
            },
            {
                "confidence": null,
                "event": "action",
                "name": "get_video",
                "policy": null,
                "timestamp": 1556700567.20442
            },
            {
                "data": {
                    "graphql": [
                        {
                            "playList": [
                                "movie-a",
                                "movie-b",
                                "c",
                                "d"
                            ],
                            "video": "http://somehost/somevideo"
                        }
                    ]
                },
                "event": "bot",
                "text": null,
                "timestamp": 1556700567.2044382
            }
        ],
        "followup_action": null,
        "latest_action_name": "get_video",
        "latest_event_time": 1556700567.2044382,
        "latest_input_channel": null,
        "latest_message": {
            "entities": [],
            "intent": {},
            "text": null
        },
        "paused": false,
        "sender_id": "jack",
        "slots": {
            "business_email": null,
            "company": null,
            "email": null,
            "job_function": null,
            "person_name": null,
            "who": null
        }
    }
}

```

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by BlankRain** [comment]
this PR also related to https://github.com/RasaHQ/rasa_core/pull/1896

**Comment by akelad** [comment]
Thanks for submitting this PR, we'll give it a review as soon as possible

**Comment by akelad** [comment]
actually sorry, i don't think we'll be accepting this PR, we're working on updating the dispatcher/output channels in general anways and I think you can do what you want to do by simply putting the stuff in `elements`. Thanks for the effort though!

**Comment by BlankRain** [comment]
@akelad  Okay, Thank you

**Comment by BlankRain** [comment]
@akelad  In fact, "simply putting the stuff in `elements`" not works. 
If I want to use `elements`, I need put my data in a `button` as button's  property.
It's a way to slove my problem. but not a good way. because it may make 'button' confused.

Here is the code :
```
       
        if message.get("elements"):
            await self.send_custom_message(recipient_id,
                                           message.get("elements"))

```


    async def send_custom_message(self,
                                  recipient_id: Text,
                                  elements: Iterable[Dict[Text, Any]]) -> None:
        """Sends elements to the output.

        Default implementation will just post the elements as a string."""

        for element in elements:
            element_msg = "{title} : {subtitle}".format(
                title=element.get('title', ''),
                subtitle=element.get('subtitle', ''))
            await self.send_text_with_buttons(
                recipient_id, element_msg, element.get('buttons', []))
```
  async def send_text_with_buttons(self, recipient_id, message, buttons,
                                     **kwargs):
        await self._persist_message(self._message(recipient_id,
                                                  text=message,
                                                  buttons=buttons))
```


This is a response with put my staff in `elements`.
```
{
    "messages": [
        {
            "buttons": [],
            "recipient_id": "hellxsxb",
            "text": "demo title : "
        }
    ],
    "tracker": {
        "active_form": {},
        "events": [
            {
                "confidence": null,
                "event": "action",
                "name": "action_listen",
                "policy": null,
                "timestamp": 1557024500.2826352
            },
            {
                "confidence": null,
                "event": "action",
                "name": "get_video",
                "policy": null,
                "timestamp": 1557024500.5989547
            },
            {
                "data": {
                    "attachment": null,
                    "buttons": null,
                    "elements": [
                        {
                            "action_name": "get_video",
                            "elements": [
                                {
                                    "subTitle": "sub video",
                                    "text": "this is a sample video",
                                    "title": "title a sample video",
                                    "video": {
                                        "controls": "controls",
                                        "src": "http://www.w3school.com.cn/i/movie.ogg"
                                    }
                                }
                            ],
                            "slots": [
                                null
                            ],
                            "subTitle": "demo sub title",
                            "title": "demo title"
                        }
                    ]
                },
                "event": "bot",
                "text": null,
                "timestamp": 1557024500.5990396
            }
        ],
        "followup_action": null,
        "latest_action_name": "get_video",
        "latest_event_time": 1557024500.5990396,
        "latest_input_channel": null,
        "latest_message": {
            "entities": [],
            "intent": {},
            "text": null
        },
        "paused": false,
        "sender_id": "hellxsxb",
        "slots": {
            "business_email": null,
            "company": null,
            "email": null,
            "job_function": null,
            "person_name": null,
            "who": null
        }
    }
}

```
and 
this is a response with put my staff in  `buttons`
```
{
    "messages": [
        {
            "buttons": [
                {
                    "subTitle": "sub video",
                    "text": "this is a sample video",
                    "title": "title a sample video",
                    "video": {
                        "controls": "controls",
                        "src": "http://www.w3school.com.cn/i/movie.ogg"
                    }
                }
            ],
            "recipient_id": "hello",
            "text": "demo title : "
        }
    ],
    "tracker": {
        "active_form": {},
        "events": [
            {
                "confidence": null,
                "event": "action",
                "name": "action_listen",
                "policy": null,
                "timestamp": 1557025371.6133947
            },
            {
                "confidence": null,
                "event": "action",
                "name": "get_video",
                "policy": null,
                "timestamp": 1557025371.6544166
            },
            {
                "data": {
                    "attachment": null,
                    "buttons": null,
                    "elements": [
                        {
                            "action_name": "get_video",
                            "buttons": [
                                {
                                    "subTitle": "sub video",
                                    "text": "this is a sample video",
                                    "title": "title a sample video",
                                    "video": {
                                        "controls": "controls",
                                        "src": "http://www.w3school.com.cn/i/movie.ogg"
                                    }
                                }
                            ],
                            "slots": [
                                null
                            ],
                            "subTitle": "demo sub title",
                            "title": "demo title"
                        }
                    ]
                },
                "event": "bot",
                "text": null,
                "timestamp": 1557025371.65445
            }
        ],
        "followup_action": null,
        "latest_action_name": "get_video",
        "latest_event_time": 1557025371.65445,
        "latest_input_channel": null,
        "latest_message": {
            "entities": [],
            "intent": {},
            "text": null
        },
        "paused": false,
        "sender_id": "hello",
        "slots": {
            "business_email": null,
            "company": null,
            "email": null,
            "job_function": null,
            "person_name": null,
            "who": null
        }
    }
}
```

you can diff the difference.

And Thank you once more.
I'm look forward so much to the updating works on `dispatcher/output channels `

**Pull request closed without merging**
